### PR TITLE
add clustered structure for mongo client.

### PR DESCRIPTION
**Pull request by utkusonmez**
We need to define all mongo urls to mongo client. Maybe it can be useful

### CODE REVIEW

**Comment by JoeHegarty** [comment]
Looks good, thanks!

**Comment by utkusonmez** [comment]
Can you notify me when new version of orbit-mongodb is released?

**Comment by JoeHegarty** [comment]
Hi @utkusonmez. The new version is now released and available on Maven Central. 
https://github.com/orbit/orbit-mongodb/releases/tag/v0.9.0

**Comment by utkusonmez** [comment]
thanks

**Pull request merged**
